include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - build/**
    - .dart_tool/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - always_declare_return_types
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - sort_constructors_first
    - sort_unnamed_constructors_first
