name: voo_offline_first
description: A Flutter package for offline-first functionality with clean architecture and automatic sync capabilities
version: 1.0.0
homepage: https://github.com/VooStack/voo_offline_first

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Data Classes
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # State Management (optional, for examples)
  flutter_bloc: ^8.1.3

  # Utils
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  drift_dev: ^2.14.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mockito: ^5.4.3

flutter:
  uses-material-design: true
