name: voo_offline_first
description: A Flutter package for offline-first functionality with clean architecture and automatic sync capabilities
version: 1.0.0
homepage: https://github.com/yourcompany/offline_first

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.34
  sqlite3: ^2.7.6
  path_provider: ^2.1.5
  path: ^1.9.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  connectivity_plus: ^5.0.0
  equatable: ^2.0.5
  uuid: ^4.5.1
  meta: ^1.16.0
  json_annotation: ^4.9.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.27.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  # Code generation dependencies
  analyzer: ^7.5.2
  build: ^2.5.4
  source_gen: ^2.0.0

flutter:
  uses-material-design: true
