name: voo_offline_first
description: A Flutter package for offline-first functionality with clean architecture and automatic sync capabilities
version: 1.0.0
homepage: https://github.com/yourcompany/offline_first

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.0

  # State Management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0

  # Network & Connectivity
  dio: ^5.3.0
  connectivity_plus: ^5.0.0

  # Utils
  equatable: ^2.0.5
  uuid: ^4.0.0
  meta: ^1.9.0
  json_annotation: ^4.8.0

  # Code Generation
  # build_runner: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation Dev Dependencies
  drift_dev: ^2.14.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
